### ISSUE TITLE
Change releases naming

### ISSUE THREAD

**Issue by whoamiUNIX** [ClusterLabs/ha_cluster_exporter#178]
Hello,

I would suggested to follow other official exporters naming. For exmaple "node-exporter", "blackbox_exporter" all this exporters follow naming in github based on releases:

For example "node exporter"
Release version 1.0.1 
node_exporter-1.0.1.linux-amd64.tar.gz 

Your release of "ha_cluster_exporter"
Release version 1.2.0
ha_cluster_exporter-amd64

Is possible to include file in "tar.gz" and include version into naming. This simple change make a really simple ansible automation where I only change version and then I can obtain new release or older if required.

I use "get_url" module where I pass {{ version }} via group variables in ansible. Let me know if this is possible or not. If not simply close this.

**Comment by stefanotorresi** [comment]
We did had the version name in the binary but we removed it because the version is present in the path itself, e.g.:

`https://github.com/ClusterLabs/ha_cluster_exporter/releases/download/1.2.0/ha_cluster_exporter-amd64`

**Comment by MalloZup** [comment]
@whoamiUNIX  hi thx for issue.

can you share here your automation more explicitly  so we can have look and maybe provide you an hint how to get the pkg?

I think that somehow with ansible you could get the latest new version without relying on a tarball version but looking at GitHub url.

**Comment by whoamiUNIX** [comment]
@MalloZup Yes, I need to download exporter and then store it in [orcharhino](https://orcharhino.com/en/) side. Target systems are not connected to internet due security reason. I have separated repository where I store exporter and then I deploy it via ansible on target nodes. The problem here is that when I download it here it contain version only in github URL. If version is directly mentioned in "tar.gz" then I can directly from my orcharhino download specific version. Now I must rename your package and put version here to know exact version. Also I do compression as I think is better to have compressed file.

**Comment by stefanotorresi** [comment]
We can add compression no problem, but I'm afraid we're not adding the version to the name just for your specific use case.
Besides, you can name your downloaded files however you desire!

You can just put the version in the destination of your download operation, e.g.:
```yaml
- name: download ha_cluster_exporter binary
  get_url:
    url: https://github.com/ClusterLabs/ha_cluster_exporter/releases/download/{{ version }}/ha_cluster_exporter-amd64
    dest: /your/path/to/ha_cluster_exporter-{{ version }}-whatever-name-suffix-you-want
```
