### ISSUE TITLE
HA Cluster configuration sample is erroneous

### ISSUE THREAD

**Issue by schniber** [ClusterLabs/ha_cluster_exporter#206]
Hello,

I have been attempting to launch the HA Cluster Exporter through the use of the config file you have provided in here:
https://github.com/ClusterLabs/ha_cluster_exporter/blob/main/ha_cluster_exporter.yaml

Steps to reproduce:

1. install the HA Cluster Exporter
2. copy the content of the cluster config yaml sample in /etc/ha_cluster_exporter.yaml
3. run /usr/bin/ha_cluster_exporter

Error message is as follows:

```
ts=2022-11-09T00:24:09.410Z caller=ha_cluster_exporter.go:265 level=info msg="Starting ha_cluster_exporter (version=1.3.0+git.1653405719.2a65dfc, branch=, revision=)"
ts=2022-11-09T00:24:09.410Z caller=ha_cluster_exporter.go:266 level=info msg="Build context (go=go1.19.1, user=, date=)"
ts=2022-11-09T00:24:09.410Z caller=ha_cluster_exporter.go:274 level=info msg="Using config file: /etc/ha_cluster_exporter.yaml"
ts=2022-11-09T00:24:09.410Z caller=ha_cluster_exporter.go:288 level=info msg="pacemaker collector registered."
ts=2022-11-09T00:24:09.410Z caller=ha_cluster_exporter.go:288 level=info msg="corosync collector registered."
ts=2022-11-09T00:24:09.410Z caller=ha_cluster_exporter.go:288 level=info msg="sbd collector registered."
ts=2022-11-09T00:24:09.410Z caller=ha_cluster_exporter.go:288 level=info msg="drbd collector registered."
ts=2022-11-09T00:24:09.411Z caller=ha_cluster_exporter.go:328 level=info msg="Serving metrics on 0.0.0.0:9664/metrics"
ts=2022-11-09T00:24:09.411Z caller=ha_cluster_exporter.go:337 level=info msg="Using web config file: /etc/ha_cluster_exporter.yaml"
ts=2022-11-09T00:24:09.411Z caller=ha_cluster_exporter.go:342 level=error msg="Error starting HTTP server" err="yaml: unmarshal errors:\n  line 1: field web not found in type web.Config\n  line 6: field log not found in type web.Config\n  line 9: field crm-mon-path not found in type web.Config\n  line 10: field cibadmin-path not found in type web.Config\n  line 11: field corosync-cfgtoolpath-path not found in type web.Config\n  line 12: field corosync-quorumtool-path not found in type web.Config\n  line 13: field sbd-path not found in type web.Config\n  line 14: field sbd-config-path not found in type web.Config\n  line 15: field drbdsetup-path not found in type web.Config"
```

so it looks like the sample file has indentation issues.

I therefore fixed the indentation to match the following :

```
web:
  listen-address: "0.0.0.0:9664"
  telemetry-path: "/metrics"
  config:
    file: "/etc/ha_cluster_exporter.yaml"
    log:
      level: "info"
      format: "logfmt"
    crm-mon-path: "/usr/sbin/crm_mon"
    cibadmin-path: "/usr/sbin/cibadmin"
    corosync-cfgtoolpath-path: "/usr/sbin/corosync-cfgtool"
    corosync-quorumtool-path: "/usr/sbin/corosync-quorumtool"
    sbd-path: "/usr/sbin/sbd"
    sbd-config-path: "/etc/sysconfig/sbd"
    drbdsetup-path: "/sbin/drbdsetup"
```

but I still don't know how to deal with the remaining error:
```
line 1: field web not found in type web.Config
```

I tried to add a web attribute inside the config map but it does not look like it is solving the issue :
```
web:
  listen-address: "0.0.0.0:9664"
  telemetry-path: "/metrics"
  config:
    web: "test"
    file: "/etc/ha_cluster_exporter.yaml"
    log:
      level: "info"
      format: "logfmt"
    crm-mon-path: "/usr/sbin/crm_mon"
    cibadmin-path: "/usr/sbin/cibadmin"
    corosync-cfgtoolpath-path: "/usr/sbin/corosync-cfgtool"
    corosync-quorumtool-path: "/usr/sbin/corosync-quorumtool"
    sbd-path: "/usr/sbin/sbd"
    sbd-config-path: "/etc/sysconfig/sbd"
    drbdsetup-path: "/sbin/drbdsetup"
```

is it possible to explain what is expected from the ha_cluster_exporter for the attribute web which should be in web.config ?

I tried to have a look in here but it's not obvious : https://github.com/ClusterLabs/ha_cluster_exporter/blob/main/ha_cluster_exporter.go#L78-#L154

also the test go function does not look like it's using a config file but it takes command line flags.
=> It would be great to include this in a test case.

Thanks in advance for your feedback.

Bests.
