### ISSUE TITLE
wrong default web-config file

### ISSUE THREAD

**Issue by sadon** [ClusterLabs/ha_cluster_exporter#239]
I got wrong responce trying to use default config file

`caller=ha_cluster_exporter.go:359 level=error msg="Error starting HTTP server" err="yaml: unmarshal errors:\n  line 2: field web not found in type web.Config\n  line 7: field log not found
` 

default config
 ````
# cat /etc/ha_cluster_exporter.web.yaml
# sample config
web:
  listen-address: "0.0.0.0:9664"
  telemetry-path: "/metrics"
  config:
    file: "/etc/ha_cluster_exporter.web.yaml"
log:
  level: "info"
  format: "logfmt"
crm-mon-path: "/usr/sbin/crm_mon"
cibadmin-path: "/usr/sbin/cibadmin"
corosync-cfgtoolpath-path: "/usr/sbin/corosync-cfgtool"
corosync-quorumtool-path: "/usr/sbin/corosync-quorumtool"
sbd-path: "/usr/sbin/sbd"
sbd-config-path: "/etc/sysconfig/sbd"
drbdsetup-path: "/sbin/drbdsetup"
````
